# tasks file for ansible-wso2ei - Specific for CentOS

- name: install required rpm and software
  apt:
    name: "{{ item }}"
    state: present
  with_items:
   - zip
   - unzip
   - rsync
  tags:
   - apt
