- name: Check if the drivers files are present
  stat:
    path: "{{ carbon_base }}/{{ wso2_app_directory }}/lib/{{ oracle_driver }}"
  register: oracle_driver_deployed

- name: Copy the database drivers 
  become: true
  become_method: sudo
  become_user: "{{ wso2_user }}"
  copy:
    src: "{{ wso2_app_archive }}/{{ item }}"
    dest: "{{ carbon_base }}/{{ wso2_app_directory }}/lib/"
    mode: 0644
  with_items:
    - "{{ oracle_driver }}"
  when: not oracle_driver_deployed.stat.exists

