- name: Check if the drivers files are present
  stat:
    path: "{{ carbon_base }}/{{ wso2_app_directory }}/lib/{{ db_driver }}"
  register: db_driver_deployed
  tags:
    - db_driver

- name: Copy the database drivers 
  become: true
  become_method: sudo
  become_user: "{{ wso2_user }}"
  copy:
    src: "{{ wso2_dir_archive }}/{{ item }}"
    dest: "{{ carbon_base }}/{{ wso2_app_directory }}/lib/"
    mode: 0644
  with_items:
    - "{{ db_driver }}"
  when: not db_driver_deployed.stat.exists
  tags:
    - db_driver

- name: Templates for config.
  become: true
  become_method: sudo
  become_user: "{{ wso2_user }}"
  template:
    src: "{{ wso2_app_version }}/{{ item }}.j2"
    dest: "{{ carbon_base }}/{{ wso2_app_directory }}/conf/{{ item }}"
    mode: 0644
  with_items:
    - carbon.xml
    - registry.xml
    - user-mgt.xml
  tags:
    - ei-config

- name: Templates for security/
  become: true
  become_method: sudo
  become_user: "{{ wso2_user }}"
  template:
    src: "{{ wso2_app_version }}/security/{{ item }}.j2"
    dest: "{{ carbon_base }}/{{ wso2_app_directory }}/conf/security/{{ item }}"
    mode: 0644
  with_items:
    - Owasp.CsrfGuard.Carbon.properties
  tags:
    - ei-config


- name: Template axis2.xml 
  become: true
  become_method: sudo
  become_user: "{{ wso2_user }}"
  template:
    src: "{{ wso2_app_version }}/axis2/axis2.xml.j2"
    dest: "{{ carbon_base }}/{{ wso2_app_directory }}/conf/axis2/axis2.xml"
    mode: 0644
  tags:
    - ei-config
    - axis2

- name: Template master-datasource.xml 
  become: true
  become_method: sudo
  become_user: "{{ wso2_user }}"
  template:
    src: "{{ wso2_app_version }}/datasources/master-datasources.xml.j2"
    dest: "{{ carbon_base }}/{{ wso2_app_directory }}/conf/datasources/master-datasources.xml"
    mode: 0644
  tags:
    - ei-config
    - datasources
