---
# handlers file for klousiaj.wso2-esb
- name: restart wso2-app
  become: true
  become_method: sudo
  systemd:
    name: "inope-{{ wso2_app }}" 
    state: restarted
- name: reload systemd
  become: true
  systemd: 
    name: "inope-{{ wso2_app }}"
    daemon_reload: yes

